import Head from "next/head";
import React from "react";
// import Navbar from "./Navbar";

const Layout: React.FC = (props) => {
  return (
    <div>
      <Head>
        <title>QuickNote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
      <main className="">{props.children}</main>
    </div>
  );
};

export default Layout;
